name       : system-tools-backends
version    : 2.10.2
release    : 8
source     :
    - https://download.gnome.org/sources/system-tools-backends/2.10/system-tools-backends-2.10.2.tar.gz : 7cb20795e540424ae2b5bde862ad0ec62ab616c21e209d6cdfca0ce7e6bdceaa
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE System Tools Backends
description: |
    MATE System Tools Backends
builddeps  :
    - pkgconfig(dbus-glib-1)
    - perl-net-dbus
rundeps    :
    - perl-xml-twig
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-basic-Solus-support-until-we-replace-this-awful-.patch
    %patch -p1 < $pkgfiles/05_fix_selfconfig.patch
    %patch -p1 < $pkgfiles/06_fix_policy_user_root.patch

    %configure --with-stb-group=stb-admin \
               --with-dbus-sys=/usr/share/dbus-1/system.d \
               --with-net-dbus=/usr/lib64/perl5
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/gnome-system-tools.conf $installdir/%libdir%/sysusers.d/gnome-system-tools.conf
